services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: trackflow-admin
      POSTGRES_PASSWORD: trackflow@123
      POSTGRES_DB: trackflow-dev
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    restart: always
    environment:
      MINIO_ROOT_USER: trackflow-admin
      MINIO_ROOT_PASSWORD: trackflow@123
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'   # S3 API
      - '9001:9001'   # Web UI
    volumes:
      - minio-data:/data

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      sh -c "
      sleep 5 &&
      mc alias set local http://minio:9000 minioadmin minioadmin123 &&
      mc mb -p local/chatapp-media || true &&
      mc anonymous set public local/chatapp-media
      "

volumes:
  pgdata:
  minio-data: